### ISSUE TITLE
Train the GAN model on my own ECGs

### ISSUE THREAD

**Issue by Bsingstad** [vlbthambawita/deepfake-ecg#1]
Hi

Is it possible to train the GAN model on my own ECGs?
Would have been nice to train the model on ECGs with a certain pathology for instance.

Maybe you could post a short tutorial/notebook on how to train the GAN model?

**Comment by vlbthambawita** [comment]
Yes, you can follow our development branch at https://github.com/vlbthambawita/Pulse2Pulse
