### ISSUE TITLE
Which guarantees are provided by the method?

### ISSUE THREAD

**Issue by AlexanderMath** [vlbthambawita/deepfake-ecg#2]
Sorry, I was a bit confused by the following:

"Although these synthetic ECGs mimic the dataset used for creation, the ECGs are not linked to any individuals and may thus be used freely. "

**Q1.** Are you able to provide any mathematical guarantees that ensure the synthetic data is "not linked" to real data?

**Q2.** If the generator model is public through Pip, I don't see how it is sufficient to guarantee synthetic and real data are "not linked"? Yes, an adversary cannot get sensitive information by generating new samples. But the adversary has the generator model and could use gradient-based attacks to learn things about the training data from the generator model.

I apologize if I am misunderstanding something. I was expecting something like differential privacy guarantees (https://en.wikipedia.org/wiki/Differential_privacy), but I wasn't able to find differential privacy anywhere in the article (including related work). Is there a reason differential privacy was not mentioned in related work? Maybe this is completely unrelated. If so, I apologize for any misunderstanding. 

**Q3.** Suppose I can attack the model and reconstruct some of the training data. What happens? How confident are you that this is impossible? If we were to bet, would you give me 1 to 100 odds?

**Q4.** Is there any reason you choose to use GANs instead of Normalizing Flows, Variational AutoEncoders or Autoregressive models? I ask because I think we may be able to get mathematical guarantees on the amount of information a likelihood model (e.g. normalizing flow) can leak about the training data.

**Comment by AlexanderMath** [comment]
Continuing discussion offline, closing issue for now.

**Comment by vlbthambawita** [comment]
> I have similar questions about the privacy guarantees provided by the method. Can you explain how much are you confident with the privacy of synthetic ECG? Thanks

We have not done any privacy specific experiments to calculate privacy preserving matrices. However, we tested generated data with the MUSE analysis system and we noticed that ECG features of the generated data are different from original, but distribution is same. Is this clear for you?
